# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questiondb', '0002_auto_20170618_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[(('t', 'text'), ('m', 'multiple choice'))], default='t', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='body_html',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
